media_folder: "experiment/images"
backend:
  name: github
  repo: chir263/test-exp
  branch: master

collections:
  - name: "Experiment"
    label: "test-exp-1"
    folder: "/experiment"
    create: false
    slug: "experiment"
    delete: false
    fields: 
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
        